# Generated by Django 2.1.15 on 2020-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200707_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Content Pilot', max_length=100),
        ),
    ]
