# Generated by Django 2.1.15 on 2020-08-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200812_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titles',
        ),
    ]
