# Generated by Django 3.1.1 on 2020-09-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200905_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Choose', on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Category'),
        ),
    ]
