# Generated by Django 3.1.1 on 2020-09-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='afoniumcore/static/assets/img/default.jpg', upload_to='profile_pics'),
        ),
    ]
